ARG base

FROM $base 

# Add cloud-init and open-vm-tools
RUN dnf -y install cloud-init open-vm-tools \
      --nodocs --setopt=install_weak_deps=False && \
    dnf clean all && \
    rm -rf /var/{cache,log} && \
    ln -s ../cloud-init.target /usr/lib/systemd/system/default.target.wants && \
    systemctl enable vmtoolsd.service

