instance_name: "fido-device-01"
ami: ami-03975b976bebb4cb8
instance_type: t3.medium
subnet_id: subnet-053842037f4ad3df0
security_group_id: sg-033428bf5df380f8b
storage: 128
microshift: false
device_count: 1
user_data_template: ./templates/user-data-fido.j2
manufacturing_server: http://ec2-13-202-44-205.ap-south-1.compute.amazonaws.com:8038