apiVersion: v1beta1
kind: AuthProvider
metadata:
  name: flightctl-cli-auth-provider
spec:
  providerType: oidc
  displayName: "FlightCTL CLI"
  issuer: "https://sso.flightctl.edgedemos.io/realms/flightctl"
  clientId: "874979da-2f06-4ab8-9112-2cfb58ce62cb"
  clientSecret: ""
  enabled: true
  scopes:
    - openid
    - profile
    - email
    - roles
    - offline_access
  usernameClaim:
    - upn
  organizationAssignment:
    type: static
    organizationName: default
  roleAssignment:
    type: dynamic
    claimPath:
      - groups
    separator: ':'