ARG FROM

FROM $FROM

RUN dnf install -y 'dnf-command(copr)' && \
    dnf copr enable -y '@fedora-iot/fedora-iot' && \
    dnf install -y go-fdo-client && \
    dnf copr disable -y @fedora-iot/fedora-iot