FROM quay.io/fedora/fedora-bootc:latest

# Install FlightCTL agent
ARG FLIGHTCTL_VERSION=1.0.2
RUN dnf -y install dnf5-plugins && \
    dnf -y config-manager addrepo --from-repofile=https://rpm.flightctl.io/flightctl-fedora.repo && \
    dnf -y install flightctl-agent${FLIGHTCTL_VERSION:+-${FLIGHTCTL_VERSION}} \
      --nodocs --setopt=install_weak_deps=False && \
    dnf clean all && \
    rm -rf /var/{cache,log}

